import {z} from "zod";
const point=z.tuple([z.number(),z.number()]);
const base=z.object({id:z.string(),type:z.enum(["rectangle","ellipse","diamond","arrow","line","freedraw","text","image","group"]),x:z.number(),y:z.number(),width:z.number(),height:z.number(),angle:z.number(),strokeColor:z.string(),backgroundColor:z.string(),fillStyle:z.enum(["solid","hachure","cross-hatch","zigzag"]),strokeWidth:z.number(),strokeStyle:z.enum(["solid","dashed","dotted"]),roughness:z.number(),opacity:z.number(),groupIds:z.array(z.string()).nullable(),frameId:z.string().nullable(),index:z.string().nullable(),roundness:z.object({type:z.number(),seed:z.number().optional()}).nullable(),seed:z.number(),versionNonce:z.number(),isDeleted:z.boolean(),boundElements:z.array(z.object({id:z.string(),type:z.enum(["arrow","text"])})).nullable(),updated:z.number(),link:z.string().nullable(),locked:z.boolean()}).passthrough();
export const ExcalidrawElementSchema=z.discriminatedUnion("type",[base.extend({type:z.literal("rectangle")}),base.extend({type:z.literal("ellipse")}),base.extend({type:z.literal("diamond")}),base.extend({type:z.literal("group")}),base.extend({type:z.literal("line"),points:z.array(point)}),base.extend({type:z.literal("arrow"),points:z.array(point),startBinding:z.unknown().nullable(),endBinding:z.unknown().nullable(),startArrowhead:z.enum(["arrow","bar","dot","triangle"]).nullable(),endArrowhead:z.enum(["arrow","bar","dot","triangle"]).nullable()}),base.extend({type:z.literal("freedraw"),points:z.array(point),simulatePressure:z.boolean(),lastCommittedPoint:point.nullable()}),base.extend({type:z.literal("text"),fontSize:z.number(),fontFamily:z.number(),text:z.string(),textAlign:z.enum(["left","center","right"]),verticalAlign:z.enum(["top","middle","bottom"]),containerId:z.string().nullable(),originalText:z.string(),lineHeight:z.number(),baseline:z.number()}),base.extend({type:z.literal("image"),fileId:z.string().nullable(),status:z.enum(["pending","saved","error"]),scale:point})]);
export const ExcalidrawSceneSchema=z.object({type:z.literal("excalidraw"),version:z.number(),source:z.string(),elements:z.array(ExcalidrawElementSchema),appState:z.record(z.string(),z.unknown()),files:z.record(z.string(),z.unknown())}).passthrough();
export const CreateElementInputSchema=z.object({element:ExcalidrawElementSchema});
export const UpdateElementInputSchema=z.object({id:z.string(),updates:z.record(z.string(),z.unknown()).default({})});
export const DeleteElementInputSchema=z.object({id:z.string()});
export const QueryElementsInputSchema=z.object({ids:z.array(z.string()).optional(),type:z.string().optional(),includeDeleted:z.boolean().default(false)});
